version: '3'
services:
  db:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: alexey
      POSTGRES_PASSWORD: example
      POSTGRES_DB: root
    ports:
      - '5431:5432' # another port to run if you have installed postgres
